### ISSUE TITLE
How is the hash calculated and why is it not used by the buildpack

### ISSUE THREAD

**Issue by michaellihs** [cloudfoundry-samples/cf-ex-phpmyadmin#12]
Hi!

We just wanted to update the phpmyadmin version from 4.8.3 to 4.8.4 and stumbled over the `PHPMYADMIN_HASH` and couldn't figure out how this is calcuted (it seems not to be the SHA hashes provided on the download page).

After further investigation, I found out that the HASH is not used at all in the PHP Buildpack: https://github.com/cloudfoundry/php-buildpack/blob/master/lib/build_pack_utils/cloudfoundry.py#L167

```python
    def install_binary_direct(self, url, hsh, installDir,
            fileName=None, strip=False,
            extract=True):

        if not fileName:
            fileName = urlparse(url).path.split('/')[-1]
        fileToInstall = os.path.join(self._ctx['TMPDIR'], fileName)

        self._log.debug("Installing direct [%s]", url)
        self._dwn.custom_extension_download(url, url, fileToInstall)

        if extract:
            return self._unzipUtil.extract(fileToInstall,
                    installDir,
                    strip)
        else:
            shutil.copy(fileToInstall, installDir)
            return installDir
```

So maybe you could

1. provide a documentation on how the SHA can be obtained
2. explain why it is not processed by the buildpack

thanks a lot,

Michael

**Comment by dmikusa-pivotal** [comment]
If this is still of concern, please open an issue against the buildpack itself. https://github.com/cloudfoundry/php-buildpack/issues. Thanks
