### ISSUE TITLE
How to create an upload directory to (xtra) large sql file?

### ISSUE THREAD

**Issue by yzimmermann** [cloudfoundry-samples/cf-ex-phpmyadmin#14]
I basically want a solution like in this so post https://stackoverflow.com/questions/11305516/how-to-import-large-sql-file-in-phpmyadmin

by creating a folder "upload" and set it as the upload directory in php config.

**Comment by dmikusa-pivotal** [comment]
You should be able to do that just edit [this file](https://github.com/cloudfoundry-samples/cf-ex-phpmyadmin/blob/master/htdocs/config.inc.php) and create an `upload` folder with your big file before you `cf push`.
