### ISSUE TITLE
mysqli_real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by adamwinn** [cloudfoundry-samples/cf-ex-phpmyadmin#16]
When I deploy my app, I'm getting
`mysqli_real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known`
and
`mysqli_real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known`

My guess is it sounds like the DB hostname is unreachable.  I have verified that `$mysql_services` in `config.inc.php` has found the mysql service and it is correct.

It is an Aurora mysql instance.  It has a public IP address that I can connect to fine with a standalone mysql client with no ssh tunneling or anything like that

```
---
applications:
- name: xxx-db
  memory: 128M
  instances: 1
  path: .
  buildpacks:
    - php_buildpack
  disk_quota: 2G
  stack: cflinuxfs3
  services:
    - xxx-aurora-mysql
```

```
System-Provided:
{
 "VCAP_SERVICES": {
  "user-provided": [
   {
    "binding_name": null,
    "credentials": {
     "hostname": "xxx.us-east-1.rds.amazonaws.com ",
     "name": "xxx",
     "password": "xxx",
     "port": "3306",
     "username": "xxx"
    },
    "instance_name": "xxx-aurora-mysql",
    "label": "user-provided",
    "name": "xxx-aurora-mysql",
    "syslog_drain_url": "",
    "tags": [],
    "volume_mounts": []
   }
  ]
 }
}

{
 "VCAP_APPLICATION": {
  "application_id": "xxx",
  "application_name": "xxx",
  "application_uris": [
   "xxx.cfapps.io"
  ],
  "application_version": "xxx",
  "cf_api": "https://api.run.pivotal.io",
  "limits": {
   "disk": 2048,
   "fds": 16384,
   "mem": 128
  },
  "name": "xxx",
  "organization_id": "xxx",
  "organization_name": "xxx",
  "process_id": "xxx",
  "process_type": "web",
  "space_id": "xxx",
  "space_name": "xxx",
  "uris": [
   "xxx.cfapps.io"
  ],
  "users": null,
  "version": "xxx"
 }
}

No user-defined env variables have been set

No running env variables have been set

No staging env variables have been set
```

**Comment by dmikusa-pivotal** [comment]
Not really sure. There's no arguing with the network library though. If it can't resolve the name, then it can't resolve the name. You'd just have to do some investigation to see why. Try `cf ssh` to the container and see if you can pull the value from the VCAP_SERVICES env variable and use it with dig/ping/mysql.

Only thing that jumps out to me, and this could just be a copy/paste error is that there's a space on the end of your hostname, `"xxx.us-east-1.rds.amazonaws.com "`. Not sure if that would cause a problem, but everything else looks normal.

**Comment by adamwinn** [comment]
Good catch!  The space after the hostname was the issue.  Thanks so much!!
