### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by louangehirwa1** [cloudfoundry-samples/cf-ex-phpmyadmin#17]
I have a local file which selects all data from my local mysql DB table and display them.
I created a hosted DB using mysql workbench and credentials of my clearDB service and added the table.

How am i going to run it in this example here? Please Help

**Comment by dmikusa-pivotal** [comment]
Sorry, I don't really follow what you are trying to do. 

The [README.md](https://github.com/cloudfoundry-samples/cf-ex-phpmyadmin/blob/master/README.md) explains how you can run this example. The example is meant to be run on Cloud Foundry, not locally. It can be extended to consume any database that is bound to the application (service binding is a feature of Cloud Foundry), although the example is set to work with ClearDB or Pivotal MySQL. If you're running your own database, you'll need to create a user-provided service with the credentials and bind that to the application. In addition, you're going to need to adjust [the service selection logic](https://github.com/cloudfoundry-samples/cf-ex-phpmyadmin/blob/master/htdocs/config.inc.php#L24-L48) to pick your user-provided service.

Hope that helps!

**Comment by louangehirwa1** [comment]
The Truth is, I had an app on PCF in which i struggled to connect to mysql
database.
I referred to your codes and thanks God, It is working now!

THANK YOU!!

**Comment by dmikusa-pivotal** [comment]
Great, glad you were able to get it working!
