### ISSUE TITLE
offline use

### ISSUE THREAD

**Issue by alexvasseur** [cloudfoundry-samples/cf-ex-phpmyadmin#6]
Is there some way to have the phpMyAdmin-4.4.11-english.tar.gz downloaded manually before cf push so that this works offline  (without using otherwise a static buildpack separate application?)
Where the tar.gz should be - or what simplification needs to be made to the .extension script for this?

**Comment by dmikusa-pivotal** [comment]
I haven't tried this, but I think it should work if you change the URL to point to a `file://` resource.

https://github.com/dmikusa-pivotal/cf-ex-phpmyadmin/blob/master/.extensions/phpmyadmin/extension.py#L18

Then you would just need to upload the .tar.gz with your application and make sure the `file://` URL points to the .tar.gz that you uploaded.  I think `file://{BUILD_DIR}/{PHPMYADMIN_PACKAGE}` would point to `phpMyAdmin-4.4.11-english.tar.gz` in the root of your application.

Hope that helps!

**Comment by avasseur-pivotal** [comment]
It looks like {BUILD_DIR} is not evaluated yet at that line of code
```
Installing PHPMyAdmin 4.4.11
Traceback (most recent call last):
  File "/tmp/buildpacks/a430273ab7c41b6b56c95fe2ee77fa76/scripts/compile.py", line 50, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/app/.extensions/phpmyadmin/extension.py", line 45, in compile
    DEFAULTS['PHPMYADMIN_URL'],
  File "/tmp/buildpacks/a430273ab7c41b6b56c95fe2ee77fa76/lib/build_pack_utils/builder.py", line 208, in extensions
    process_extension(path, ctx, 'compile', process, args=[self])
  File "/tmp/buildpacks/a430273ab7c41b6b56c95fe2ee77fa76/lib/build_pack_utils/utils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
  File "/tmp/buildpacks/a430273ab7c41b6b56c95fe2ee77fa76/lib/build_pack_utils/utils.py", line 151, in __getitem__
    return self.format(dict.__getitem__(self, key))
  File "/tmp/buildpacks/a430273ab7c41b6b56c95fe2ee77fa76/lib/build_pack_utils/utils.py", line 142, in format
    val = val.format(**self)
KeyError: 'BUILD_DIR'
Failed to compile droplet```

**Comment by dmikusa-pivotal** [comment]
OK, I see what's happening.  BUILD_DIR get's set very early, but the DEFAULTS here is it's own set of options and isn't part of the global context so it doesn't know about BUILD_DIR.  Try editing this line instead.

https://github.com/dmikusa-pivotal/cf-ex-phpmyadmin/blob/master/.extensions/phpmyadmin/extension.py#L42

Put in `"file://%s/%s" % (ctx['BUILD_DIR'], DEFAULTS['PHPMYADMIN_PACKAGE']),` instead.  That should pull the BUILD_DIR from the ctx and package name from DEFAULTS.  Or you could just hard code the path for BUILD_DIR.  I think it's something like `/tmp/staged/app` or `/tmp/app`, but it shouldn't change so it's not the end of the world to hard code it.
