### ISSUE TITLE
AWS Aurora support

### ISSUE THREAD

**Issue by bbodensieck** [cloudfoundry-samples/cf-ex-phpmyadmin#7]
Hi,
I would like to use this great project in our cloudfoundry. Our mysql service is named aws_aurora. So this does not contain „mysql“ in the service type. I tried to go through the code and modified the config but a am not able to get a connection (error in „real mysql connect“). But I was able to connect via ssh tunnel and can send sql queries by console.

Would be great if you support this or either give me a hint how to modify it.

Best regards
Björn

**Comment by dmikusa-pivotal** [comment]
This code here is likely what you need to modify.

https://github.com/cloudfoundry-samples/cf-ex-phpmyadmin/blob/master/htdocs/config.inc.php#L27-L66

What's there in the code attempts to read the information for your bound services and configure PHP MyAdmin to be able to connect to the bound services. If it's not doing what you want, you can try to adjust the code but you can also just configure your specific service credentials.

You'd just need to configure PHP MyAdmin for your service as described in the docs here.

https://docs.phpmyadmin.net/en/latest/config.html#server-connection-settings
