### ISSUE TITLE
Getting mysqli_real_connect(): (HY000/2002): No such file or directory

### ISSUE THREAD

**Issue by vlvanchin** [cloudfoundry-samples/cf-ex-phpmyadmin#8]
Dear Team,

I have an issue where i am not allowed to logon to the phpmyadmin web app after entering my credentials in the login form.

Please guide me on this.
Thank you so much,

vanchin

**Comment by dmikusa-pivotal** [comment]
Hard to say. I would suggest checking the `config.inc.php` that is being used to see if there are issues there. That is where the server configuration is defined.
